add env vars
vimc/montagu-orderly-web pull request #1
Opened 2019-06-12 15:42 UTC by hillalex

2019-06-13 12:52 UTC, richfitz requested changes

2019-06-13 12:52 UTC, richfitz commented on config/orderly-web.yml
> +    MONTAGU_HOST: db,
trailing comma here should be removed I think

2019-06-13 12:52 UTC, richfitz commented on config/science.yml
> +    ANNEX_PASSWORD: VAULT:secret/database/science/users/readonly:password
Should be `VAULT:secret/annex/users/readonly:password`

2019-06-13 12:52 UTC, richfitz commented on config/prod.yml
> +    ANNEX_PASSWORD: VAULT:secret/database/production/users/readonly:password
Should be `VAULT:secret/annex/users/readonly:password`

2019-06-13 14:08 UTC, EmmaLRussell reviewed
I guess we don't need a value in github_org. 
Do we want to include 'master' in the tag values, or a placeholder that will be replaced by version tag by deployment script?

2019-06-14 10:14 UTC, hillalex commented
> I guess we don't need a value in github_org.
> Do we want to include 'master' in the tag values, or a placeholder that will be replaced by version tag by deployment script?

I think this ticket was intended to work that out: https://vimc.myjetbrains.com/youtrack/issue/mrc-291

2019-06-14 15:22 UTC, merged