scripts to run montagu on different instances
vimc/montagu-orderly-web pull request #3
Opened 2019-06-13 13:29 UTC by hillalex

2019-06-13 13:34 UTC, hillalex commented
Actually I guess we also want scripts to stop each of these. Ok ignore this, refactoring.

2019-06-14 15:27 UTC, richfitz requested changes

2019-06-14 15:27 UTC, richfitz commented on setup.sh
> +#!/usr/bin/env bash
could you make this file be called `setup` (no `.sh` suffix) & similar for the other scripts

2019-06-14 15:27 UTC, richfitz commented on start.sh
> +    exit 0
should be `exit 1` to indicate failure

2019-06-14 15:27 UTC, richfitz commented on setup.sh
> +    exit 0
should be exit 1 throughout

2019-06-14 15:27 UTC, richfitz commented on start.sh
> +set -ex
can you drop the `x` option to clear up the output? (and in the others)

2019-06-14 15:27 UTC, richfitz commented on setup.sh
> +if [[ "$1" = "uat" ]] || [[ "$1" = "science" ]] || [[ "$1" = "prod" ]] ; then
`prod` should be `production` to match our names elsewhere I think

2019-06-17 11:17 UTC, richfitz approved these changes

2019-06-17 13:54 UTC, EmmaLRussell approved these changes

2019-06-17 13:54 UTC, merged